# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0c69dd891dc83e468733a1bac34c447d541c562c076508b8295342d0d676d70d39bc810b249f7e8082f01592dcb31b759e8d01ea563c31bc058c42ea872a5d7

test:
  secret_key_base: 1da09e463780548dcad7d0e2bb2c2546908c4c5e55e237af94e042ea7bb4a7109a6a6dfd2e00baa5932a82dd5542b30610e2b3982018aa92b8e1825817d18121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
